# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

source 'https://git.coding.net/MasonHe/GeneralRepo.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'OfflineBreakpointDownload' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OfflineBreakpointDownload
  pod 'FMDB'
#  pod 'MBProgressHUDExtension'


end
